apiVersion: v1
kind: ConfigMap
metadata:
  name: commafeed-configmap
data:
  QUARKUS_DATASOURCE_JDBC_URL: psql-commafeed
  QUARKUS_DATASOURCE_USERNAME: "commafeed"
  QUARKUS_DATASOURCE_PASSWORD: "commafeed"
