apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n-postgres
resources:
  - ../../base/commafeed/
  - cloudflare.yaml
  - commafeed-container-env-secret.yaml
  - cf-tunnel-commafeed-adstage.yaml
  - ingress.yaml
  - configmap.yaml
  - postgresql-secret.yaml
