apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000

      containers:
        - name: metabase
          image: metabase/metabase:v0.60.1
          ports:
            - name: http
              containerPort: 3000

          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1536Mi

          envFrom:
            - configMapRef:
                name: metabase-configmap
          env:
            - name: MB_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: password
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx1g"

          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            seccompProfile:
              type: "RuntimeDefault"
            capabilities:
              drop:
                - ALL

          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 300
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 240
            periodSeconds: 10
            failureThreshold: 3

          volumeMounts:
            - name: tmp
              mountPath: /tmp

      volumes:
        - name: tmp
          emptyDir: {}
