apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../../_base/kube-prometheus-stack
patches:
  - patch: |
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: kube-prometheus-stack
      spec:
        values:
          grafana:
            ingress:
              enabled: false
            service:
              type: NodePort
              nodePort: 32000
