apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-credentials
  namespace: velero
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: velero-credentials
    template:
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .root_user }}
          aws_secret_access_key={{ .root_password }}
  data:
    - secretKey: root_user
      remoteRef:
        key: /minio/ROOT_USER
    - secretKey: root_password
      remoteRef:
        key: /minio/ROOT_PASSWORD
