apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rclone-credentials
  namespace: velero
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: rclone-credentials
  data:
    - secretKey: MINIO_ACCESS_KEY_ID
      remoteRef:
        key: /minio/ROOT_USER
    - secretKey: MINIO_SECRET_ACCESS_KEY
      remoteRef:
        key: /minio/ROOT_PASSWORD
    - secretKey: R2_ACCESS_KEY_ID
      remoteRef:
        key: /r2/ACCESS_KEY_ID
    - secretKey: R2_SECRET_ACCESS_KEY
      remoteRef:
        key: /r2/SECRET_ACCESS_KEY
    - secretKey: R2_ENDPOINT
      remoteRef:
        key: /r2/ENDPOINT
    - secretKey: R2_BUCKET
      remoteRef:
        key: /r2/BUCKET
