apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
data:
  bookmarks.yaml: |
    ---
    # For configuration options and examples, please see:
    # https://gethomepage.dev/configs/bookmarks

    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/GAlexandruD

    - Social:
        - Reddit:
            - abbr: RE
              href: https://reddit.com/

    - Entertainment:
        - YouTube:
            - abbr: YT
              href: https://youtube.com/

  custom.css: ""

  custom.js: ""

  docker.yaml: |
    ---
    # For configuration options and examples, please see:
    # https://gethomepage.dev/configs/docker/

    # my-docker:
    #   host: 127.0.0.1
    #   port: 2375

  kubernetes.yaml: |
    ---
    # sample kubernetes config

  proxmox.yaml: |
    ---
    # pve:
    #   url: https://proxmox.host.or.ip:8006
    #   token: username@pam!Token ID
    #   secret: secret

  services.yaml: |
    ---
    # For configuration options and examples, please see:
    # https://gethomepage.dev/configs/services/

    - adstage:
        - Quartz:
            href: https://blog-adstage.alexandrud.com/
            description: Blog running on Quartz
            icon: blogger
        - N8n:
            href: https://n8n-adstage.alexandrud.com/
            description: Great automations
            icon: n8n
        - Linkding:
            href: https://linkding-adstage.alexandrud.com/
            description: Bookmarks
            icon: linkding
        - Audiobookshelf:
            href: https://audiobookshelf-adstage.alexandrud.com/
            description: Audio books.
            icon: audiobookshelf
        - Commafeed:
            href: https://commafeed-adstage.alexandrud.com/
            description: RSS feed.
            icon: commafeed
        - NextJS-App:
            href: https://nextjs-on-docker-adstage.alexandrud.com/
            description: A NextJS app.
            icon: nextjs
        - Metabase:
            href: https://metabase-adstage.alexandrud.com/
            description: Query, visualize, and analyze data.
            icon: metabase

    - Monitoring:
        - Adstage - UptimeKuma:
            href: https://uptimekuma-adstage.alexandrud.com/status/adstage
            description: Monitors connectivity
            icon: uptime-kuma
            widget:
              type: uptimekuma
              url: https://uptimekuma-adstage.alexandrud.com
              slug: adstage

        - GrafanaMonitoring:
            href: https://grafana-adstage.alexandrud.com/public-dashboards/42f78c614ade459cabf8c235e2b14819
            description: Monitoring
            icon: grafana

    - Currently Disabled:
        - Wallabag:
            #href: https://wallabag-adstage.alexandrud.com/
            description: Read later.
            icon: wallabag

  settings.yaml: |
    ---
    # For configuration options and examples, please see:
    # https://gethomepage.dev/configs/settings/

    providers:
      openweathermap: openweathermapapikey
      weatherapi: weatherapiapikey

  widgets.yaml: |
    ---
    # For configuration options and examples, please see:
    # https://gethomepage.dev/configs/info-widgets/

    - resources:
        cpu: true
        memory: true
        disk: /

    - search:
        provider: duckduckgo
        target: _blank
