apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
  - ../../_base/homepage/
  - configmap-env.yaml
  - configmap.yaml
  - ingress.yaml
  - cloudflare.yaml
  - cf-tunnel-homepage-adstage.yaml
