apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      containers:
        - name: linkding
          image: sissbruecker/linkding:1.45.0
          ports:
            - name: http
              containerPort: 9090
          
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          
          envFrom:
            #- configMapRef:
            #    name: linkding-configmap
            - secretRef:
                name: linkding-container-env

          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: "RuntimeDefault"
            capabilities:
              drop:
                - ALL
              add:
                - CHOWN
                - SETUID
                - SETGID
                - FOWNER

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3

          volumeMounts:
            - name: linkding-data
              mountPath: /etc/linkding/data

      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-data-pvc
