apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding
resources:
  - ../../base/audiobookshelf
  - cloudflare.yaml
  - audiobookshelf-container-env-secret.yaml
  - cf-tunnel-k3s-sops.yaml
  - ingress.yaml
