apiVersion: v1
kind: Service
metadata:
  name: n8n-postgres
spec:
  ports:
    - port: 5680 # The port exposed by the Service
      targetPort: 5678 # The port inside the container
  selector:
    app: n8n-postgres
  type: ClusterIP
