apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextjs-on-docker
resources:
  - ../../base/nextjs-on-docker/
  - cloudflare.yaml
  #- audiobookshelf-container-env-secret.yaml
  - cf-tunnel-stg-nextjs-on-docker.yaml
  - ingress.yaml
