apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-config-maxipi
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/WD1TB/nfs/k8s/pvc-df6fe5cb-e34c-4e78-8863-037d9dbd2811
    type: Directory
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - maxipi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-downloads-maxipi
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/WD1TB/nfs/k8s/pvc-fba0f65d-7eb9-4071-a6f3-09bb6268d8ad
    type: Directory
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - maxipi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-watch-maxipi
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/WD1TB/nfs/k8s/pvc-5126ed73-70df-4b07-abba-3b14c3ac452c
    type: Directory
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - maxipi
