apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-koofr-credentials
  namespace: velero
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: velero-koofr-credentials
    template:
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .access_key_id }}
          aws_secret_access_key={{ .secret_access_key }}
  data:
    - secretKey: access_key_id
      remoteRef:
        key: /velero/KOOFR_ACCESS_KEY_ID
    - secretKey: secret_access_key
      remoteRef:
        key: /velero/KOOFR_SECRET_ACCESS_KEY
