apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rclone-credentials
  namespace: velero
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: rclone-credentials
  data:
    - secretKey: MINIO_ACCESS_KEY_ID
      remoteRef:
        key: /minio/ROOT_USER
    - secretKey: MINIO_SECRET_ACCESS_KEY
      remoteRef:
        key: /minio/ROOT_PASSWORD
    - secretKey: KOOFR_USER
      remoteRef:
        key: /velero/KOOFR_ACCESS_KEY_ID
    - secretKey: KOOFR_PASSWORD
      remoteRef:
        key: /velero/KOOFR_SECRET_ACCESS_KEY
    - secretKey: GDRIVE_TOKEN
      remoteRef:
        key: /velero/GDRIVE_TOKEN
