apiVersion: v1
kind: Service
metadata:
  name: n8n-postgresql
spec:
  ports:
    - port: 5679 # The port exposed by the Service
      targetPort: 5679 # The port inside the container
  selector:
    app: n8n-postgresql
  type: ClusterIP
