apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-postgres-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  #storageClassName: sata # Used for spot.rackspace.com

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  #storageClassName: sata # Used for spot.rackspace.com
