apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: immich-secrets
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: /immich/SECRET_KEY
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /immich/DB_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-db-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: immich-db-secret
  data:
    - secretKey: password
      remoteRef:
        key: /immich/DB_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cf-tunnel-immich-maxipi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: cf-tunnel-immich-maxipi
  data:
    - secretKey: credentials.json
      remoteRef:
        key: /immich/CF_TUNNEL_IMMICH_CREDENTIALS
