apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - ../../_base/immich
  - pv.yaml
  - externalsecret.yaml
  - cloudflare.yaml
  - tailscale-ingress.yaml
images:
  - name: ghcr.io/immich-app/immich-server
    newTag: "v3.0.2"
  - name: ghcr.io/immich-app/immich-machine-learning
    newTag: "v3.0.2"
  - name: ghcr.io/immich-app/postgres
    newTag: "14-vectorchord0.4.3-pgvectors0.2.0"
  - name: valkey/valkey
    newTag: "9"
  - name: busybox
    newTag: "1.36"
patches:
  - target:
      kind: Deployment
      name: immich-server
    patch: |
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          kubernetes.io/hostname: maxipi
      - op: add
        path: /spec/template/spec/securityContext/supplementalGroups
        value: [993]
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: dri
          hostPath:
            path: /dev/dri
            type: Directory
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: dri
          mountPath: /dev/dri
