apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Ti
  storageClassName: nfs-csi-8tb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgresql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-csi-8tb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-ml-cache-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-csi-8tb
