apiVersion: v1
kind: Service
metadata:
  name: nextjs-on-docker
spec:
  ports:
    - port: 3006    # The port exposed by the Service
      targetPort: 3000   # The port inside the container
  selector:
    app: nextjs-on-docker
  type: ClusterIP 
