apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: minio-credentials
  data:
    - secretKey: MINIO_ROOT_USER
      remoteRef:
        key: /minio/ROOT_USER
    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef:
        key: /minio/ROOT_PASSWORD
