apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio
resources:
  - ../../_base/minio
images:
  - name: quay.io/minio/minio
    newTag: "RELEASE.2025-09-07T16-13-09Z-cpuv1"
  - externalsecret.yaml
  - pv.yaml
patches:
  - patch: |-
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: minio-data
        namespace: minio
      spec:
        storageClassName: ""
        volumeName: minio-data-maxipi
        resources:
          requests:
            storage: 500Gi
