apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: postgresql-secret
  data:
    - secretKey: password
      remoteRef:
        key: METABASE_DB_PASSWORD
        secretPath: /metabase
        projectSlug: adstage-z2wz
        environmentSlug: staging
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cf-tunnel-metabase-adstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: cf-tunnel-metabase-adstage
  data:
    - secretKey: credentials.json
      remoteRef:
        key: CF_TUNNEL_METABASE_CREDENTIALS
        secretPath: /metabase
        projectSlug: adstage-z2wz
        environmentSlug: staging
