apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: postgresql-secret
  data:
    - secretKey: password
      remoteRef:
        key: /metabase/METABASE_DB_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cf-tunnel-metabase-adstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: cf-tunnel-metabase-adstage
  data:
    - secretKey: credentials.json
      remoteRef:
        key: /metabase/CF_TUNNEL_METABASE_CREDENTIALS
