apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding
resources:
  - ../../base/linkding
  - cloudflare.yaml
  - linkding-container-env-secret.yaml
  - cf-tunnel-linkding-adstage.yaml
  - ingress.yaml
