apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cf-tunnel-quartz-adstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: cf-tunnel-quartz-adstage
  data:
    - secretKey: credentials.json
      remoteRef:
        key: /quartz/CF_TUNNEL_QUARTZ_CREDENTIALS
