apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: transmission
resources:
  - ../../_base/transmission
  #- transmission-container-env-secret.yaml
images:
  - name: lscr.io/linuxserver/transmission
    newTag: "4.1.3"

