apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallabag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallabag
  template:
    metadata:
      labels:
        app: wallabag
    spec:
      # envsubst in the entrypoint sh needs to write to /etc/php
      #securityContext:
      #  fsGroup: 1000 # node group ID
      #  runAsUser: 1000 # node user ID
      #  runAsGroup: 1000 # node group ID

      containers:
        - name: wallabag
          image: wallabag/wallabag:2.6.13

          envFrom:
            - configMapRef:
                name: wallabag-configmap
            - secretRef:
                name: postgresql-secret

          env:
            - name: SYMFONY__ENV__DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: password
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: password

          securityContext:
            allowPrivilegeEscalation: false

          volumeMounts:
            - name: wallabag-data
              mountPath: web/assets/images

      volumes:
        - name: wallabag-data
          persistentVolumeClaim:
            claimName: wallabag-data-pvc
