apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallabag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallabag
  template:
    metadata:
      labels:
        app: wallabag
    spec:
      securityContext:
        fsGroup: 65534
        runAsUser: 65534
        runAsGroup: 65534
      containers:
        - name: wallabag
          image: wallabag/wallabag:2.6.14

          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

          envFrom:
            - configMapRef:
                name: wallabag-configmap
            - secretRef:
                name: postgresql-secret

          env:
            - name: SYMFONY__ENV__DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: password
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: password

          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            seccompProfile:
              type: "RuntimeDefault"
            capabilities:
              drop:
                - ALL

          ports:
            - name: http
              containerPort: 80

          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3

          volumeMounts:
            - name: wallabag-data
              mountPath: web/assets/images
            - name: app-config
              mountPath: /var/www/wallabag/app/config
            - name: tmp
              mountPath: /tmp
            - name: php-conf
              mountPath: /etc/php81/conf.d
            - name: var
              mountPath: /var/www/wallabag/var

      volumes:
        - name: wallabag-data
          persistentVolumeClaim:
            claimName: wallabag-data-pvc
        - name: app-config
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: php-conf
          emptyDir: {}
        - name: var
          emptyDir: {}

