apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallabag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallabag
  template:
    metadata:
      labels:
        app: wallabag
    spec:
      securityContext:
        fsGroup: 65534 # GID for fs

      containers:
        - name: wallabag
          image: wallabag/wallabag:2.6.14

          envFrom:
            - configMapRef:
                name: wallabag-configmap
            - secretRef:
                name: postgresql-secret

          env:
            - name: SYMFONY__ENV__DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: password
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: password

          securityContext:
            # runAsUser: 65534 # UID for nobody
            # runAsGroup: 65534 # GID for nobody
            allowPrivilegeEscalation: false

          volumeMounts:
            - name: wallabag-data
              mountPath: web/assets/images
            - name: wallabag-php-config
              mountPath: /etc/php81/conf.d/50_wallabag.ini.test
              subPath: 50_wallabag.ini
              readOnly: true

      volumes:
        - name: wallabag-data
          persistentVolumeClaim:
            claimName: wallabag-data-pvc
        - name: wallabag-php-config
          configMap:
            name: wallabag-php-config
            items:
              - key: 50_wallabag.ini
                path: 50_wallabag.ini
