apiVersion: v1
kind: Service
metadata:
  name: wallabag
spec:
  ports:
    - port: 80 # The port exposed by the Service
      targetPort: 80 # The port inside the container
  selector:
    app: wallabag
  type: ClusterIP
