apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      securityContext:
        fsGroup: 1000 # node group ID
        #runAsUser: 1000 # node user ID
        #runAsGroup: 1000 # node group ID

      containers:
        - name: transmission
          image: lscr.io/linuxserver/transmission:4.1.1
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - containerPort: 9091 # Expose the 9091 port.
              name: web
            - containerPort: 51413
              name: tcp
            - containerPort: 51413
              name: udp
              protocol: UDP
            
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

          envFrom:
            #- configMapRef:
            #    name: linkding-configmap
            #- secretRef:
            #    name: transmission-container-env

          securityContext:
            allowPrivilegeEscalation: false
            #runAsNonRoot: true
            readOnlyRootFilesystem: true
            seccompProfile:
              type: "RuntimeDefault"
            capabilities:
              drop:
                - ALL

          livenessProbe:
            tcpSocket:
              port: web
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: web
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3

          volumeMounts:
            - name: transmission-config
              mountPath: /config

            - name: transmission-downloads
              mountPath: /downloads

            - name: transmission-watch
              mountPath: /watch

            - name: run
              mountPath: /run

      volumes:
        - name: transmission-config
          persistentVolumeClaim:
            claimName: transmission-config-pvc

        - name: transmission-downloads
          persistentVolumeClaim:
            claimName: transmission-downloads-pvc

        - name: transmission-watch
          persistentVolumeClaim:
            claimName: transmission-watch-pvc

        - name: run
          emptyDir: {}

