apiVersion: v1
kind: Service
metadata:
  name: transmission
spec:
  ports:
    - port: 9091 # The port exposed by the Service
      targetPort: 9091 # The port inside the container
      name: web
    - port: 51413 # The port exposed by the Service
      targetPort: 51413 # The port inside the container
      name: tcp
    - port: 51413 # The port exposed by the Service
      targetPort: 51413 # The port inside the container
      protocol: UDP
      name: udp
  selector:
    app: transmission
  type: ClusterIP
