apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  #storageClassName: sata # Used for spot.rackspace.com

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-downloads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  #storageClassName: sata # Used for spot.rackspace.com

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-watch-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  #storageClassName: sata # Used for spot.rackspace.com

