apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: operator-oauth
  data:
    - secretKey: clientId
      remoteRef:
        key: /tailscale/OAUTH_CLIENT_ID
    - secretKey: clientSecret
      remoteRef:
        key: /tailscale/OAUTH_CLIENT_SECRET
