apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wallabag
spec:
  ingressClassName: traefik
  rules:
    - host: notset.alexandrud.com
      http:
        paths:
          - backend:
              service:
                name: wallabag
                port:
                  number: 80
            path: /
            pathType: Prefix
