apiVersion: v1
data:
    adminPassword: ENC[AES256_GCM,data:c5Yd2BbY/r5i+N4ehrFxT/CHMN+FAZ+jOMlftA==,iv:SVU6hsCyxk17mbvP10t9CjM2PbNz/G4NGyjH6Oe+YV0=,tag:4LaOmujrOPfs5SuD4ww5lg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: grafana-admin-secret
sops:
    age:
        - recipient: age1fl9l0r80p7pzfur27fa7vhyjcq9nsm6tnzfrknsc2muyezk28fgsnfxtpp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwaEMwYnBpcFZtZVVNVER0
            WDIrdHVjRmloU1V1RGlNN3pDbXJWZ0tydXlrCkhGWnc4LzkxcXpvc1BwZ1cvVUhk
            emlQdDhrc0dLNzFRclAxMFptUEdvc1kKLS0tIFNaQmZBRXFSWmZPdUkwUGpwVWVM
            YlFUT1krUFRyVUVrZTNxWkg4RVdkVm8KvWe18PPCKpxNBPPI1Mr4tUBw1MYj8gNP
            xJ1Q4D4jUQgCBTxyuruKy4RMzzl8CbGruwwHefCk/F+JlCPqR7iUAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-25T10:08:12Z"
    mac: ENC[AES256_GCM,data:gapCGBzeo/FpEZMGAFs4DNa6kM1R1Xj1yWP1csZqX+WiQmi3urhzEW6wI/yJ1CH/1T371uiJWbW+DzeOUvs/wQDxaDhhCVE5A93htHFnZD1KkW3oyboO28B7KdRtxc6Dqb9syYEI3AISlMpT159euFnHhFUNmZ44uYXZS5tfupQ=,iv:u/h5EuvS76MiQAgMjjaAUagBPDzzYWGnh4+9127YH/g=,tag:/K0L4dy7plfzbofPPiwx8A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
