apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: grafana-admin-secret
  data:
    - secretKey: adminUser
      remoteRef:
        key: /grafana/ADMIN_USER
    - secretKey: adminPassword
      remoteRef:
        key: /grafana/ADMIN_PASSWORD
