apiVersion: v1
kind: Service
metadata:
  name: commafeed
spec:
  ports:
    - port: 8082 # The port exposed by the Service
      targetPort: 8082 # The port inside the container
  selector:
    app: commafeed
  type: ClusterIP
